server: 
  host: 0.0.0.0
  port: 8080
  metricsPort: 8081
  minValidYear: 2018
log:
  level: info
tzkt:
  timeout: 10
  url: https://api.tzkt.io
  retryAttempts: 3
db:
  user: postgres
  dbname: delegations 
  password: postgres
  host: localhost
  port: 5432
poller:
  startLevel: 5479747
  retryAttempts: 3
  fetchOld: true

  
