server: 
  host: 0.0.0.0
  port: 8080
log:
  level: info
validation:
  startYear: 2018
tzkt:
  timeout: 10
  url: https://api.tzkt.io
  startLevel: 5440000
db:
  user: postgres
  dbname: delegations 
  password: postgres
  host: localhost
  port: 5432
metrics:
  port: 8081
