server: 
  host: 0.0.0.0
  port: 8080
  metricsPort: 8081
  minValidYear: 2018
log:
  level: debug
tzkt:
  timeout: 10
  url: https://api.tzkt.io
db:
  user: postgres
  dbname: delegations 
  password: postgres
  host: localhost
  port: 5432
poller:
  startLevel: 5470000
  
