version: '3.1'

services:
  db:
    container_name: 'postgres'
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delegations
  # tezos-delegation-watcher:
  #   container_name: 'tezos-delegation-watcher'
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"  
  #     - "8081:8081"  
  #   depends_on:
  #     - db
